### ISSUE TITLE
Typo in CASE statement

### ISSUE THREAD

**Issue by dsmdavid** [zsombor-flds/dbt-jinja-cheatsheet#1]
Thanks for putting together this cheatsheet! 👍 

<img width="397" alt="image" src="https://user-images.githubusercontent.com/11340545/165403684-f8e6301b-4d3c-472d-8d53-1346f5699fd9.png">

Likely that second `WHEN` should be a `THEN`

**Comment by zsombor-flds** [comment]
@dsmdavid Good catch!  Thanks I updated it.
